#!/usr/bin/env bash

FUNC=$1

PROJ="handy-coil-235818"
CONF_FILE="config.yml"
ENV_FILE="env.yml"

echo "Deploy $FUNC to $PROJ using env: $ENV_FILE, config: $CONF_FILE"

gcloud functions deploy $FUNC \
--project $PROJ \
--runtime go111 \
--trigger-http \
--env-vars-file $ENV_FILE